// import mongoose from "mongoose";

// import dns from "dns";
// dns.setServers(['8.8.8.8', '8.8.4.4']);

// import "dotenv/config"
// import { v2 as cloudinary } from "cloudinary";
// import Product from "./models/Product.js";
// import path from "path"
// import { dirname } from 'path';
// import { fileURLToPath } from 'url';

// const _filename = fileURLToPath(import.meta.url);
// const _dirname = dirname(_filename);

// const dummyProducts = [
//     {
//         title: "Green Astatic Bangles",
//         images: ["Product1.webp"],
//         price: { "2-10": 15, "2-12": 25, "2-14": 40 },
//         description: "Elegant green glass bangles with a glossy finish that enhances your look. Lightweight and comfortable for long wear. Perfect for daily styling and small occasions. A timeless addition to your collection.",
//         category: "Glass Bangle",
//         type: "Daily Wear",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Green Astatic Bangles",
//         images: ["Product2.webp"],
//         price: { "2-10": 20, "2-12": 35, "2-14": 50 },
//         description: "Premium green bangles set designed to add vibrance to your outfit. Features a polished shine for festive occasions. Ideal for weddings and celebrations. Complements traditional attire beautifully.",
//         category: "Glass Bangle",
//         type: "Festive",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: true,
//         inStock: true,
//     },
//     {
//         title: "Astatic pink Bangle",
//         images: ["Product3.webp"],
//         price: { "2-10": 25, "2-12": 40, "2-14": 60 },
//         description: "Soft pink bangles with a delicate and feminine appeal. Designed for comfort with a stylish finish. Perfect for casual outings and light occasions. Adds grace to any look.",
//         category: "Glass Bangle",
//         type: "Casual",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Delicious Pink Bangles",
//         images: ["Product4.webp"],
//         price: { "2-10": 18, "2-12": 30, "2-14": 45 },
//         description: "Beautiful pink bangles crafted with a refined finish. Durable and long-lasting shine. Perfect for festive and traditional wear. Enhances your ethnic appearance.",
//         category: "Glass Bangle",
//         type: "Traditional",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: true,
//         inStock: true,
//     },
//     {
//         title: "Long Hand Multi set",
//         images: ["Product5.webp"],
//         price: { "2-10": 22, "2-12": 38, "2-14": 55 },
//         description: "Long multi-set bangles designed for a complete bridal look. Rich patterns provide a luxurious feel. Ideal for weddings and heavy outfits. A perfect festive accessory.",
//         category: "Multi Set",
//         type: "Bridal",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Long Hand Multi Set",
//         images: ["Product6.webp"],
//         price: { "2-10": 28, "2-12": 45, "2-14": 65 },
//         description: "Elegant multi-set bangles with intricate detailing. Gives a royal and premium look. Suitable for grand celebrations and weddings. Comfortable and stylish.",
//         category: "Multi Set",
//         type: "Bridal",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Choclately Red Nag Bangle",
//         images: ["Product7.webp"],
//         price: { "2-10": 12, "2-12": 20, "2-14": 35 },
//         description: "Deep red bangles with a bold glossy finish. Designed for eye-catching festive looks. Perfect for parties and weddings. Adds richness to your outfit.",
//         category: "Glass Bangle",
//         type: "Party Wear",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Choclately Red Nag Bangle",
//         images: ["Product8.webp"],
//         price: { "2-10": 25, "2-12": 40, "2-14": 60 },
//         description: "Chocolate red bangles with smooth and shiny texture. Stylish and comfortable for long wear. Ideal for traditional functions. A modern ethnic choice.",
//         category: "Glass Bangle",
//         type: "Ethnic",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Simple Dark red Bangle",
//         images: ["Product9.webp"],
//         price: { "2-10": 30, "2-12": 50, "2-14": 75 },
//         description: "Simple dark red bangles with a classic minimal design. Perfect for daily wear and comfort. Lightweight and versatile. Matches every outfit easily.",
//         category: "Glass Bangle",
//         type: "Daily Wear",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: true,
//         inStock: true,
//     },
//     {
//         title: "Dark Brown Amazing Kada",
//         images: ["Product10.webp"],
//         price: { "2-10": 40, "2-12": 60, "2-14": 85 },
//         description: "Premium brown kada with a bold and sturdy design. Perfect for statement styling. Ideal for traditional and party wear. Adds elegance to your look.",
//         category: "Kada Bangle",
//         type: "Designer",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Multi Color Nag bangles",
//         images: ["Product11.webp"],
//         price: { "2-10": 45, "2-12": 65, "2-14": 90 },
//         description: "Multi-color bangles with vibrant and eye-catching tones. Perfect for festive celebrations. Adds energy to your outfit. Stylish and trendy.",
//         category: "Glass Bangle",
//         type: "Festive",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Multi Color Nag Bangle",
//         images: ["Product12.webp"],
//         price: { "2-10": 35, "2-12": 55, "2-14": 80 },
//         description: "Colorful bangles set designed for mix-and-match styling. Bright and attractive finish. Ideal for casual and festive wear. Enhances overall look.",
//         category: "Glass Bangle",
//         type: "Casual",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Single set Multi Bangles",
//         images: ["Product13.webp"],
//         price: { "2-10": 42, "2-12": 62, "2-14": 88 },
//         description: "Single set bangles with balanced color combination. Elegant and simple design. Suitable for daily and festive wear. Comfortable fit.",
//         category: "Glass Bangle",
//         type: "Traditional",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: true,
//         inStock: true,
//     },
//     {
//         title: "Single Designed Kada",
//         images: ["Product14.webp"],
//         price: { "2-10": 38, "2-12": 58, "2-14": 82 },
//         description: "Designer kada with unique patterns and finish. Strong and stylish structure. Ideal for modern ethnic styling. Perfect for occasions.",
//         category: "Kada Bangle",
//         type: "Designer",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Spicy Matalic Small Hand Set",
//         images: ["Product15.webp"],
//         price: { "2-10": 44, "2-10": 64, "2-14": 89 },
//         description: "Metallic multi-set bangles with shiny finish. Designed for party and festive looks. Adds glamour to your outfit. Lightweight and stylish.",
//         category: "Multi Set",
//         type: "Party Wear",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Fancy Multi Matalic Hand Set",
//         images: ["Product16.webp"],
//         price: { "2-10": 36, "2-12": 56, "2-14": 81 },
//         description: "Fancy metallic bangles set with modern design. Premium look with smooth edges. Perfect for events and celebrations. Comfortable wear.",
//         category: "Multi Set",
//         type: "Designer",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Exotic Many Colors Set",
//         images: ["Product17.webp"],
//         price: { "2-10": 48, "2-12": 70, "2-14": 95 },
//         description: "Exotic colorful bangles set for grand occasions. Rich design enhances ethnic outfits. Perfect for weddings and celebrations. Stylish choice.",
//         type: "Bridal",
//         category: "Multi Set",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Large Many Colors Set",
//         images: ["Product18.webp"],
//         price: { "2-10": 39, "2-12": 59, "2-14": 84 },
//         description: "Large multi-color bangles set for bold styling. Designed for festive and wedding wear. Adds volume and beauty. Premium finish.",
//         type: "Festive",
//         category: "Multi Set",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: true,
//         inStock: true,
//     },
//     {
//         title: "Piped Set Redly Bangle Set",
//         images: ["Product19.webp"],
//         price: { "2-10": 25, "2-12": 40, "2-14": 60 },
//         description: "Red piped bangles with detailed finishing. Elegant and traditional design. Perfect for festive occasions. Comfortable for long wear.",
//         type: "Traditional",
//         category: "Glass Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Brightening Redly piped Bangle",
//         images: ["Product20.webp"],
//         price: { "2-10": 28, "2-12": 45, "2-14": 65 },
//         description: "Bright red bangles with polished shine. Stylish and vibrant appearance. Ideal for parties and festivals. Enhances ethnic outfits.",
//         type: "Party Wear",
//         category: "Glass Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Retinol Anti Set Bangles",
//         images: ["Product21.webp"],
//         price: { "2-10": 30, "2-12": 50, "2-14": 70 },
//         description: "Designer bangles set with elegant patterns. Modern and stylish look. Perfect for special occasions. Durable and lightweight.",
//         type: "Designer",
//         category: "Glass Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Niacinamide Balancing Kada bangles",
//         images: ["Product22.webp"],
//         price: { "2-10": 22, "2-12": 35, "2-14": 55 },
//         description: "Stylish kada bangles with bold finish. Strong and long-lasting material. Ideal for modern traditional wear. Comfortable fit.",
//         type: "Ethnic",
//         category: "Kada Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Peptide 4-paired Set",
//         images: ["Product23.webp"],
//         price: { "2-10": 32, "2-12": 52, "2-14": 75 },
//         description: "Multi-set bangles with balanced design. Suitable for daily and festive use. Elegant color combination. Easy to style.",
//         type: "Traditional",
//         category: "Multi Set",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Volumizing 4-paired Set",
//         images: ["Product24.webp"],
//         price: { "2-10": 15, "2-12": 25, "2-14": 40 },
//         description: "4-paired bangles set for a complete look. Lightweight and comfortable design. Ideal for casual styling. Simple yet elegant.",
//         type: "Casual",
//         category: "Multi Set",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Valvate 3rd Paired Big Set",
//         images: ["Product25.webp"],
//         price: { "2-10": 18, "2-12": 30, "2-14": 45 },
//         description: "Large multi-set bangles perfect for weddings. Rich and premium appearance. Designed for heavy outfits. Adds festive charm.",
//         type: "Bridal",
//         category: "Multi Set",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: true,
//         inStock: true,
//     },
//     {
//         title: "Clarifying 4-Paired Set Bangles",
//         images: ["Product26.webp"],
//         price: { "2-10": 20, "2-12": 35, "2-14": 50 },
//         description: "Paired bangles with modern stylish design. Perfect for casual and daily wear. Lightweight and trendy. Easy to carry.",
//         type: "Casual",
//         category: "Multi Set",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: true,
//         inStock: true,
//     },
//     {
//         title: "Anti-Dandruff Colored Bangle",
//         images: ["Product27.webp"],
//         price: { "2-10": 16, "2-12": 28, "2-14": 42 },
//         description: "Colored bangles with vibrant finish. Simple yet attractive design. Ideal for daily use. Comfortable and durable.",
//         type: "Daily Wear",
//         category: "Glass Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Protect Dark Voilet Kada Bangle",
//         images: ["Product28.webp"],
//         price: { "2-10": 19, "2-12": 32, "2-14": 48 },
//         description: "Dark violet kada with bold appearance. Stylish and modern design. Perfect for statement looks. Long-lasting finish.",
//         type: "Designer",
//         category: "Kada Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Citrus Designed Red Bangle",
//         images: ["Product29.webp"],
//         price: { "2-10": 12, "2-12": 20, "2-14": 35 },
//         description: "Red designer bangles with unique color tone. Stylish and trendy look. Ideal for casual and festive wear. Lightweight design.",
//         type: "Casual",
//         category: "Glass Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Cool Red Mint Kade",
//         images: ["Product30.webp"],
//         price: { "2-10": 14, "2-12": 22, "2-14": 38 },
//         description: "Cool-toned kada with refreshing design. Modern and minimal look. Suitable for daily styling. Comfortable wear.",
//         type: "Daily Wear",
//         category: "Kada Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Vanilla Dream Redly lined Kade",
//         images: ["Product31.webp"],
//         price: { "2-10": 13, "2-12": 21, "2-14": 36 },
//         description: "Soft red kada with smooth finish. Elegant and simple design. Perfect for light occasions. Stylish and durable.",
//         type: "Traditional",
//         category: "Kada Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Ocean Wave Paired Kade",
//         images: ["Product32.webp"],
//         price: { "2-10": 15, "2-12": 25, "2-14": 40 },
//         description: "Ocean-inspired kada with fresh colors. Trendy and modern appeal. Perfect for casual styling. Lightweight and stylish.",
//         type: "Casual",
//         category: "Kada Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: true,
//         inStock: true,
//     },
//     {
//         title: "Berry Pink Simple Bangles",
//         images: ["Product33.webp"],
//         price: { "2-10": 11, "2-12": 18, "2-14": 32 },
//         description: "Pink simple bangles with minimal design. Elegant and easy to wear. Suitable for daily use. Matches all outfits.",
//         type: "Daily Wear",
//         category: "Glass Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Gentle Foaming Tiranga kade",
//         images: ["Product34.webp"],
//         price: { "2-10": 15, "2-12": 25, "2-14": 40 },
//         description: "Tiranga-themed kada with unique colors. Stylish and meaningful design. Perfect for special occasions. Comfortable fit.",
//         type: "Ethnic",
//         category: "Kada Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Golden Cleanser Delicious Kade",
//         images: ["Product35.webp"],
//         price: { "2-10": 18, "2-12": 30, "2-14": 45 },
//         description: "Golden kada with rich premium finish. Elegant and eye-catching design. Ideal for festive wear. Enhances traditional outfits.",
//         type: "Festive",
//         category: "Kada Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Fancy Stand Delicious 2-paired Kade",
//         images: ["Product36.webp"],
//         price: { "2-10": 20, "2-12": 35, "2-14": 50 },
//         description: "Fancy paired kada with stylish structure. Modern and attractive design. Perfect for parties. Lightweight comfort.",
//         type: "Party Wear",
//         category: "Kada Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: true,
//         inStock: true,
//     },
//     {
//         title: "Exfoliating Red-Gold Bangle",
//         images: ["Product37.webp"],
//         price: { "2-10": 22, "2-12": 38, "2-14": 55 },
//         description: "Red-gold bangles with elegant blend. Perfect for weddings and celebrations. Premium finish and design. Adds richness.",
//         type: "Bridal",
//         category: "Glass Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Micellar Kade Designed",
//         images: ["Product38.webp"],
//         price: { "2-10": 16, "2-12": 28, "2-14": 42 },
//         description: "Designed kada with modern patterns. Stylish and durable build. Perfect for daily and party wear. Comfortable fit.",
//         type: "Designer",
//         category: "Kada Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Antibacterial Hand-Full Set",
//         images: ["Product39.webp"],
//         price: { "2-10": 10, "2-12": 18, "2-14": 30 },
//         description: "Full-hand multi-set bangles for traditional look. Rich and stylish appearance. Ideal for festive occasions. Comfortable wear.",
//         type: "Traditional",
//         category: "Multi Set",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Moisturizing Hand Voilet Bangle",
//         images: ["Product40.webp"],
//         price: { "2-10": 12, "2-12": 20, "2-14": 35 },
//         description: "Violet glass bangles with smooth shine. Elegant and simple design. Perfect for daily styling. Lightweight comfort.",
//         type: "Daily Wear",
//         category: "Glass Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Citrus Scented Two Paired bangle",
//         images: ["Product41.webp"],
//         price: { "2-10": 11, "2-12": 19, "2-14": 32 },
//         description: "Citrus-toned bangles with vibrant look. Fresh and trendy design. Ideal for casual outfits. Easy to style.",
//         type: "Casual",
//         category: "Glass Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Lavender Calming Hand green Bangle",
//         images: ["Product42.webp"],
//         price: { "2-10": 13, "2-12": 22, "2-14": 38 },
//         description: "Green bangles with calming tone. Elegant and minimal finish. Suitable for daily wear. Comfortable and stylish.",
//         type: "Daily Wear",
//         category: "Glass Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Tree light green-yellow Bangle",
//         images: ["Product43.webp"],
//         price: { "2-10": 14, "2-12": 24, "2-14": 40 },
//         description: "Light green-yellow bangles with fresh design. Perfect for casual styling. Lightweight and comfortable. Stylish look.",
//         type: "Casual",
//         category: "Glass Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Plane Simple Bangle",
//         images: ["Product44.webp"],
//         price: { "2-10": 15, "2-12": 25, "2-14": 45 },
//         description: "Plain simple bangles with minimal design. Perfect for everyday use. Lightweight and easy to wear. Classic style.",
//         type: "Daily Wear",
//         category: "Glass Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Hydrate Many Color Bangle Set",
//         images: ["Product45.webp"],
//         price: { "2-10": 10, "2-12": 18 },
//         description: "Multi-color bangles set with vibrant tones. Ideal for mix and match styling. Perfect for casual and festive wear. Stylish design.",
//         type: "Casual",
//         category: "Glass Bangle",
//         sizes: ["2-10", "2-12"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Glossy Multi Set Kade",
//         images: ["Product46.webp"],
//         price: { "2-12": 12, "2-14": 20 },
//         description: "Glossy kada set with shiny premium finish. Stylish and modern look. Perfect for parties. Comfortable wear.",
//         type: "Party Wear",
//         category: "Kada Bangle",
//         sizes: ["2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Light Coloring Bangle",
//         images: ["Product47.webp"],
//         price: { "2-10": 18, "2-12": 30, "2-14": 45 },
//         description: "Light-colored bangles with soft elegant design. Perfect for daily use. Comfortable and stylish. Matches any outfit.",
//         type: "Daily Wear",
//         category: "Glass Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Matte Big-Bangle set",
//         images: ["Product48.webp"],
//         price: { "2-10": 14, "2-12": 24 },
//         description: "Matte finish bangles set with modern touch. Trendy and stylish look. Perfect for casual wear. Lightweight design.",
//         type: "Casual",
//         category: "Multi Set",
//         sizes: ["2-10", "2-12"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Aloe Light Blue Bangle",
//         images: ["Product49.webp"],
//         price: { "2-10": 15, "2-12": 25, "2-14": 40 },
//         description: "Light blue bangles with soothing tone. Elegant and refreshing design. Ideal for daily styling. Comfortable fit.",
//         type: "Daily Wear",
//         category: "Glass Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: true,
//         inStock: true,
//     },
//     {
//         title: "dark Natured Bangle Designed",
//         images: ["Product50.webp"],
//         price: { "2-10": 12, "2-12": 20, "2-14": 35 },
//         description: "Dark designer bangles with bold look. Stylish and modern finish. Perfect for evening wear. Durable design.",
//         type: "Designer",
//         category: "Glass Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Sea Moisturizing Designed Bangle",
//         images: ["Product51.webp"],
//         price: { "2-10": 18, "2-12": 30, "2-14": 45 },
//         description: "Sea-inspired bangles with fresh design. Stylish and unique appearance. Perfect for casual outfits. Lightweight.",
//         type: "Casual",
//         category: "Glass Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Relaxing Expensive kade set",
//         images: ["Product52.webp"],
//         price: { "2-10": 14, "2-12": 22, "2-14": 38 },
//         description: "Premium kada set with luxurious finish. Designed for special occasions. Elegant and stylish look. Comfortable fit.",
//         type: "Bridal",
//         category: "Multi Set",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Enriched Weds Set",
//         images: ["Product53.webp"],
//         price: { "2-10": 20, "2-12": 35, "2-14": 50 },
//         description: "Wedding special bangles set with rich design. Perfect for bridal wear. Enhances traditional outfits. Premium quality.",
//         type: "Bridal",
//         category: "Multi Set",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
//     {
//         title: "Unscented Sensitive Bangle",
//         images: ["Product54.webp"],
//         price: { "2-10": 16, "2-12": 28, "2-14": 42 },
//         description: "Simple kada with minimal elegant design. Perfect for daily styling. Comfortable and lightweight. Classic look.",
//         type: "Daily Wear",
//         category: "Kada Bangle",
//         sizes: ["2-10", "2-12", "2-14"],
//         popular: false,
//         inStock: true,
//     },
// ];

// cloudinary.config({
//     cloud_name: process.env.CLDN_NAME,
//     api_key: process.env.CLDN_API_KEY,
//     api_secret: process.env.CLDN_API_SECRET,
// })

// async function bulkUpload() {
//     try {
//         await mongoose.connect(`${process.env.MONGO_URI}`);

//         for(const prod of dummyProducts){
//             const imagesUrl = await Promise.all(
//                 prod.images.map(async (filename) =>{
//                     const filePath = path.join(_dirname, "images", filename);
//                     const result = await cloudinary.uploader.upload(filePath, {
//                         resource_type: "image",
//                     });
//                     return result.secure_url;
//                 })
//             );

//             await Product.create({
//                 title: prod.title,
//                 description: prod.description,
//                 price: prod.price,
//                 sizes: prod.sizes,
//                 images: imagesUrl,
//                 category: prod.category,
//                 type: prod.type,
//                 popular: prod.popular,
//                 inStock: prod.inStock,
//             });

//             console.log(`Uploader: ${prod.title}`)
//         }

//         console.log("All products uploaded successfully")

//     } catch (error) {
//         console.error("Error:", error);
//     } finally {
//         mongoose.disconnect();
//     }
// }

// bulkUpload();















import mongoose from "mongoose";

import dns from "dns";
dns.setServers(['8.8.8.8', '8.8.4.4']);

import "dotenv/config"
import { v2 as cloudinary } from "cloudinary";
import Product from "./models/Product.js";
import path from "path"
import { dirname } from 'path';
import { fileURLToPath } from 'url';

const _filename = fileURLToPath(import.meta.url);
const _dirname = dirname(_filename);

const dummyProducts = [
    {
        title: "Green Astatic Bangles",
        images: ["Product1.webp"],
        price: { "2-10": 15, "2-12": 25, "2-14": 40 },
        description: "Elegant green glass bangles with a glossy finish that enhances your look. Lightweight and comfortable for long wear. Perfect for daily styling and small occasions. A timeless addition to your collection.",
        category: "Glass Bangle",
        type: "Daily Wear",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Green Astatic Bangles",
        images: ["Product2.webp"],
        price: { "2-10": 20, "2-12": 35, "2-14": 50 },
        description: "Premium green bangles set designed to add vibrance to your outfit. Features a polished shine for festive occasions. Ideal for weddings and celebrations. Complements traditional attire beautifully.",
        category: "Glass Bangle",
        type: "Festive",
        sizes: ["2-10", "2-12", "2-14"],
        popular: true,
        inStock: true,
    },
    {
        title: "Astatic pink Bangle",
        images: ["Product3.webp"],
        price: { "2-10": 25, "2-12": 40, "2-14": 60 },
        description: "Soft pink bangles with a delicate and feminine appeal. Designed for comfort with a stylish finish. Perfect for casual outings and light occasions. Adds grace to any look.",
        category: "Glass Bangle",
        type: "Casual",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Delicious Pink Bangles",
        images: ["Product4.webp"],
        price: { "2-10": 18, "2-12": 30, "2-14": 45 },
        description: "Beautiful pink bangles crafted with a refined finish. Durable and long-lasting shine. Perfect for festive and traditional wear. Enhances your ethnic appearance.",
        category: "Glass Bangle",
        type: "Traditional",
        sizes: ["2-10", "2-12", "2-14"],
        popular: true,
        inStock: true,
    },
    {
        title: "Long Hand Multi set",
        images: ["Product5.webp"],
        price: { "2-10": 22, "2-12": 38, "2-14": 55 },
        description: "Long multi-set bangles designed for a complete bridal look. Rich patterns provide a luxurious feel. Ideal for weddings and heavy outfits. A perfect festive accessory.",
        category: "Multi Set",
        type: "Bridal",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Long Hand Multi Set",
        images: ["Product6.webp"],
        price: { "2-10": 28, "2-12": 45, "2-14": 65 },
        description: "Elegant multi-set bangles with intricate detailing. Gives a royal and premium look. Suitable for grand celebrations and weddings. Comfortable and stylish.",
        category: "Multi Set",
        type: "Bridal",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Choclately Red Nag Bangle",
        images: ["Product7.webp"],
        price: { "2-10": 12, "2-12": 20, "2-14": 35 },
        description: "Deep red bangles with a bold glossy finish. Designed for eye-catching festive looks. Perfect for parties and weddings. Adds richness to your outfit.",
        category: "Glass Bangle",
        type: "Party Wear",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Choclately Red Nag Bangle",
        images: ["Product8.webp"],
        price: { "2-10": 25, "2-12": 40, "2-14": 60 },
        description: "Chocolate red bangles with smooth and shiny texture. Stylish and comfortable for long wear. Ideal for traditional functions. A modern ethnic choice.",
        category: "Glass Bangle",
        type: "Ethnic",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Simple Dark red Bangle",
        images: ["Product9.webp"],
        price: { "2-10": 30, "2-12": 50, "2-14": 75 },
        description: "Simple dark red bangles with a classic minimal design. Perfect for daily wear and comfort. Lightweight and versatile. Matches every outfit easily.",
        category: "Glass Bangle",
        type: "Daily Wear",
        sizes: ["2-10", "2-12", "2-14"],
        popular: true,
        inStock: true,
    },
    {
        title: "Dark Brown Amazing Kada",
        images: ["Product10.webp"],
        price: { "2-10": 40, "2-12": 60, "2-14": 85 },
        description: "Premium brown kada with a bold and sturdy design. Perfect for statement styling. Ideal for traditional and party wear. Adds elegance to your look.",
        category: "Kada Bangle",
        type: "Designer",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Multi Color Nag bangles",
        images: ["Product11.webp"],
        price: { "2-10": 45, "2-12": 65, "2-14": 90 },
        description: "Multi-color bangles with vibrant and eye-catching tones. Perfect for festive celebrations. Adds energy to your outfit. Stylish and trendy.",
        category: "Glass Bangle",
        type: "Festive",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Multi Color Nag Bangle",
        images: ["Product12.webp"],
        price: { "2-10": 35, "2-12": 55, "2-14": 80 },
        description: "Colorful bangles set designed for mix-and-match styling. Bright and attractive finish. Ideal for casual and festive wear. Enhances overall look.",
        category: "Glass Bangle",
        type: "Casual",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Single set Multi Bangles",
        images: ["Product13.webp"],
        price: { "2-10": 42, "2-12": 62, "2-14": 88 },
        description: "Single set bangles with balanced color combination. Elegant and simple design. Suitable for daily and festive wear. Comfortable fit.",
        category: "Glass Bangle",
        type: "Traditional",
        sizes: ["2-10", "2-12", "2-14"],
        popular: true,
        inStock: true,
    },
    {
        title: "Single Designed Kada",
        images: ["Product14.webp"],
        price: { "2-10": 38, "2-12": 58, "2-14": 82 },
        description: "Designer kada with unique patterns and finish. Strong and stylish structure. Ideal for modern ethnic styling. Perfect for occasions.",
        category: "Kada Bangle",
        type: "Designer",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Spicy Matalic Small Hand Set",
        images: ["Product15.webp"],
        price: { "2-10": 44, "2-10": 64, "2-14": 89 },
        description: "Metallic multi-set bangles with shiny finish. Designed for party and festive looks. Adds glamour to your outfit. Lightweight and stylish.",
        category: "Multi Set",
        type: "Party Wear",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Fancy Multi Matalic Hand Set",
        images: ["Product16.webp"],
        price: { "2-10": 36, "2-12": 56, "2-14": 81 },
        description: "Fancy metallic bangles set with modern design. Premium look with smooth edges. Perfect for events and celebrations. Comfortable wear.",
        category: "Multi Set",
        type: "Designer",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Exotic Many Colors Set",
        images: ["Product17.webp"],
        price: { "2-10": 48, "2-12": 70, "2-14": 95 },
        description: "Exotic colorful bangles set for grand occasions. Rich design enhances ethnic outfits. Perfect for weddings and celebrations. Stylish choice.",
        type: "Bridal",
        category: "Multi Set",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Large Many Colors Set",
        images: ["Product18.webp"],
        price: { "2-10": 39, "2-12": 59, "2-14": 84 },
        description: "Large multi-color bangles set for bold styling. Designed for festive and wedding wear. Adds volume and beauty. Premium finish.",
        type: "Festive",
        category: "Multi Set",
        sizes: ["2-10", "2-12", "2-14"],
        popular: true,
        inStock: true,
    },
    {
        title: "Piped Set Redly Bangle Set",
        images: ["Product19.webp"],
        price: { "2-10": 25, "2-12": 40, "2-14": 60 },
        description: "Red piped bangles with detailed finishing. Elegant and traditional design. Perfect for festive occasions. Comfortable for long wear.",
        type: "Traditional",
        category: "Glass Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Brightening Redly piped Bangle",
        images: ["Product20.webp"],
        price: { "2-10": 28, "2-12": 45, "2-14": 65 },
        description: "Bright red bangles with polished shine. Stylish and vibrant appearance. Ideal for parties and festivals. Enhances ethnic outfits.",
        type: "Party Wear",
        category: "Glass Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Retinol Anti Set Bangles",
        images: ["Product21.webp"],
        price: { "2-10": 30, "2-12": 50, "2-14": 70 },
        description: "Designer bangles set with elegant patterns. Modern and stylish look. Perfect for special occasions. Durable and lightweight.",
        type: "Designer",
        category: "Glass Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Niacinamide Balancing Kada bangles",
        images: ["Product22.webp"],
        price: { "2-10": 22, "2-12": 35, "2-14": 55 },
        description: "Stylish kada bangles with bold finish. Strong and long-lasting material. Ideal for modern traditional wear. Comfortable fit.",
        type: "Ethnic",
        category: "Kada Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Peptide 4-paired Set",
        images: ["Product23.webp"],
        price: { "2-10": 32, "2-12": 52, "2-14": 75 },
        description: "Multi-set bangles with balanced design. Suitable for daily and festive use. Elegant color combination. Easy to style.",
        type: "Traditional",
        category: "Multi Set",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Volumizing 4-paired Set",
        images: ["Product24.webp"],
        price: { "2-10": 15, "2-12": 25, "2-14": 40 },
        description: "4-paired bangles set for a complete look. Lightweight and comfortable design. Ideal for casual styling. Simple yet elegant.",
        type: "Casual",
        category: "Multi Set",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Valvate 3rd Paired Big Set",
        images: ["Product25.webp"],
        price: { "2-10": 18, "2-12": 30, "2-14": 45 },
        description: "Large multi-set bangles perfect for weddings. Rich and premium appearance. Designed for heavy outfits. Adds festive charm.",
        type: "Bridal",
        category: "Multi Set",
        sizes: ["2-10", "2-12", "2-14"],
        popular: true,
        inStock: true,
    },
    {
        title: "Clarifying 4-Paired Set Bangles",
        images: ["Product26.webp"],
        price: { "2-10": 20, "2-12": 35, "2-14": 50 },
        description: "Paired bangles with modern stylish design. Perfect for casual and daily wear. Lightweight and trendy. Easy to carry.",
        type: "Casual",
        category: "Multi Set",
        sizes: ["2-10", "2-12", "2-14"],
        popular: true,
        inStock: true,
    },
    {
        title: "Anti-Dandruff Colored Bangle",
        images: ["Product27.webp"],
        price: { "2-10": 16, "2-12": 28, "2-14": 42 },
        description: "Colored bangles with vibrant finish. Simple yet attractive design. Ideal for daily use. Comfortable and durable.",
        type: "Daily Wear",
        category: "Glass Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Protect Dark Voilet Kada Bangle",
        images: ["Product28.webp"],
        price: { "2-10": 19, "2-12": 32, "2-14": 48 },
        description: "Dark violet kada with bold appearance. Stylish and modern design. Perfect for statement looks. Long-lasting finish.",
        type: "Designer",
        category: "Kada Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Citrus Designed Red Bangle",
        images: ["Product29.webp"],
        price: { "2-10": 12, "2-12": 20, "2-14": 35 },
        description: "Red designer bangles with unique color tone. Stylish and trendy look. Ideal for casual and festive wear. Lightweight design.",
        type: "Casual",
        category: "Glass Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Cool Red Mint Kade",
        images: ["Product30.webp"],
        price: { "2-10": 14, "2-12": 22, "2-14": 38 },
        description: "Cool-toned kada with refreshing design. Modern and minimal look. Suitable for daily styling. Comfortable wear.",
        type: "Daily Wear",
        category: "Kada Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Vanilla Dream Redly lined Kade",
        images: ["Product31.webp"],
        price: { "2-10": 13, "2-12": 21, "2-14": 36 },
        description: "Soft red kada with smooth finish. Elegant and simple design. Perfect for light occasions. Stylish and durable.",
        type: "Traditional",
        category: "Kada Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Ocean Wave Paired Kade",
        images: ["Product32.webp"],
        price: { "2-10": 15, "2-12": 25, "2-14": 40 },
        description: "Ocean-inspired kada with fresh colors. Trendy and modern appeal. Perfect for casual styling. Lightweight and stylish.",
        type: "Casual",
        category: "Kada Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: true,
        inStock: true,
    },
    {
        title: "Berry Pink Simple Bangles",
        images: ["Product33.webp"],
        price: { "2-10": 11, "2-12": 18, "2-14": 32 },
        description: "Pink simple bangles with minimal design. Elegant and easy to wear. Suitable for daily use. Matches all outfits.",
        type: "Daily Wear",
        category: "Glass Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Gentle Foaming Tiranga kade",
        images: ["Product34.webp"],
        price: { "2-10": 15, "2-12": 25, "2-14": 40 },
        description: "Tiranga-themed kada with unique colors. Stylish and meaningful design. Perfect for special occasions. Comfortable fit.",
        type: "Ethnic",
        category: "Kada Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Golden Cleanser Delicious Kade",
        images: ["Product35.webp"],
        price: { "2-10": 18, "2-12": 30, "2-14": 45 },
        description: "Golden kada with rich premium finish. Elegant and eye-catching design. Ideal for festive wear. Enhances traditional outfits.",
        type: "Festive",
        category: "Kada Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Fancy Stand Delicious 2-paired Kade",
        images: ["Product36.webp"],
        price: { "2-10": 20, "2-12": 35, "2-14": 50 },
        description: "Fancy paired kada with stylish structure. Modern and attractive design. Perfect for parties. Lightweight comfort.",
        type: "Party Wear",
        category: "Kada Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: true,
        inStock: true,
    },
    {
        title: "Exfoliating Red-Gold Bangle",
        images: ["Product37.webp"],
        price: { "2-10": 22, "2-12": 38, "2-14": 55 },
        description: "Red-gold bangles with elegant blend. Perfect for weddings and celebrations. Premium finish and design. Adds richness.",
        type: "Bridal",
        category: "Glass Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Micellar Kade Designed",
        images: ["Product38.webp"],
        price: { "2-10": 16, "2-12": 28, "2-14": 42 },
        description: "Designed kada with modern patterns. Stylish and durable build. Perfect for daily and party wear. Comfortable fit.",
        type: "Designer",
        category: "Kada Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Antibacterial Hand-Full Set",
        images: ["Product39.webp"],
        price: { "2-10": 10, "2-12": 18, "2-14": 30 },
        description: "Full-hand multi-set bangles for traditional look. Rich and stylish appearance. Ideal for festive occasions. Comfortable wear.",
        type: "Traditional",
        category: "Multi Set",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Moisturizing Hand Voilet Bangle",
        images: ["Product40.webp"],
        price: { "2-10": 12, "2-12": 20, "2-14": 35 },
        description: "Violet glass bangles with smooth shine. Elegant and simple design. Perfect for daily styling. Lightweight comfort.",
        type: "Daily Wear",
        category: "Glass Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Citrus Scented Two Paired bangle",
        images: ["Product41.webp"],
        price: { "2-10": 11, "2-12": 19, "2-14": 32 },
        description: "Citrus-toned bangles with vibrant look. Fresh and trendy design. Ideal for casual outfits. Easy to style.",
        type: "Casual",
        category: "Glass Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Lavender Calming Hand green Bangle",
        images: ["Product42.webp"],
        price: { "2-10": 13, "2-12": 22, "2-14": 38 },
        description: "Green bangles with calming tone. Elegant and minimal finish. Suitable for daily wear. Comfortable and stylish.",
        type: "Daily Wear",
        category: "Glass Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Tree light green-yellow Bangle",
        images: ["Product43.webp"],
        price: { "2-10": 14, "2-12": 24, "2-14": 40 },
        description: "Light green-yellow bangles with fresh design. Perfect for casual styling. Lightweight and comfortable. Stylish look.",
        type: "Casual",
        category: "Glass Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Plane Simple Bangle",
        images: ["Product44.webp"],
        price: { "2-10": 15, "2-12": 25, "2-14": 45 },
        description: "Plain simple bangles with minimal design. Perfect for everyday use. Lightweight and easy to wear. Classic style.",
        type: "Daily Wear",
        category: "Glass Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Hydrate Many Color Bangle Set",
        images: ["Product45.webp"],
        price: { "2-10": 10, "2-12": 18 },
        description: "Multi-color bangles set with vibrant tones. Ideal for mix and match styling. Perfect for casual and festive wear. Stylish design.",
        type: "Casual",
        category: "Glass Bangle",
        sizes: ["2-10", "2-12"],
        popular: false,
        inStock: true,
    },
    {
        title: "Glossy Multi Set Kade",
        images: ["Product46.webp"],
        price: { "2-12": 12, "2-14": 20 },
        description: "Glossy kada set with shiny premium finish. Stylish and modern look. Perfect for parties. Comfortable wear.",
        type: "Party Wear",
        category: "Kada Bangle",
        sizes: ["2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Light Coloring Bangle",
        images: ["Product47.webp"],
        price: { "2-10": 18, "2-12": 30, "2-14": 45 },
        description: "Light-colored bangles with soft elegant design. Perfect for daily use. Comfortable and stylish. Matches any outfit.",
        type: "Daily Wear",
        category: "Glass Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Matte Big-Bangle set",
        images: ["Product48.webp"],
        price: { "2-10": 14, "2-12": 24 },
        description: "Matte finish bangles set with modern touch. Trendy and stylish look. Perfect for casual wear. Lightweight design.",
        type: "Casual",
        category: "Multi Set",
        sizes: ["2-10", "2-12"],
        popular: false,
        inStock: true,
    },
    {
        title: "Aloe Light Blue Bangle",
        images: ["Product49.webp"],
        price: { "2-10": 15, "2-12": 25, "2-14": 40 },
        description: "Light blue bangles with soothing tone. Elegant and refreshing design. Ideal for daily styling. Comfortable fit.",
        type: "Daily Wear",
        category: "Glass Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: true,
        inStock: true,
    },
    {
        title: "dark Natured Bangle Designed",
        images: ["Product50.webp"],
        price: { "2-10": 12, "2-12": 20, "2-14": 35 },
        description: "Dark designer bangles with bold look. Stylish and modern finish. Perfect for evening wear. Durable design.",
        type: "Designer",
        category: "Glass Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Sea Moisturizing Designed Bangle",
        images: ["Product51.webp"],
        price: { "2-10": 18, "2-12": 30, "2-14": 45 },
        description: "Sea-inspired bangles with fresh design. Stylish and unique appearance. Perfect for casual outfits. Lightweight.",
        type: "Casual",
        category: "Glass Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Relaxing Expensive kade set",
        images: ["Product52.webp"],
        price: { "2-10": 14, "2-12": 22, "2-14": 38 },
        description: "Premium kada set with luxurious finish. Designed for special occasions. Elegant and stylish look. Comfortable fit.",
        type: "Bridal",
        category: "Multi Set",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Enriched Weds Set",
        images: ["Product53.webp"],
        price: { "2-10": 20, "2-12": 35, "2-14": 50 },
        description: "Wedding special bangles set with rich design. Perfect for bridal wear. Enhances traditional outfits. Premium quality.",
        type: "Bridal",
        category: "Multi Set",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
    {
        title: "Unscented Sensitive Bangle",
        images: ["Product54.webp"],
        price: { "2-10": 16, "2-12": 28, "2-14": 42 },
        description: "Simple kada with minimal elegant design. Perfect for daily styling. Comfortable and lightweight. Classic look.",
        type: "Daily Wear",
        category: "Kada Bangle",
        sizes: ["2-10", "2-12", "2-14"],
        popular: false,
        inStock: true,
    },
];

cloudinary.config({
    cloud_name: process.env.CLDN_NAME,
    api_key: process.env.CLDN_API_KEY,
    api_secret: process.env.CLDN_API_SECRET,
})

async function bulkUpload() {
    let successCount = 0;
    let failCount = 0;

    try {
        await mongoose.connect(`${process.env.MONGO_URI}`);

        for(const prod of dummyProducts){
            try {
                const imagesUrl = await Promise.all(
                    prod.images.map(async (filename) =>{
                        const filePath = path.join(_dirname, "images", filename);
                        const result = await cloudinary.uploader.upload(filePath, {
                            resource_type: "image",
                        });
                        return result.secure_url;
                    })
                );

                await Product.create({
                    title: prod.title,
                    description: prod.description,
                    price: prod.price,
                    sizes: prod.sizes,
                    images: imagesUrl,
                    category: prod.category,
                    type: prod.type,
                    popular: prod.popular,
                    inStock: prod.inStock,
                });

                console.log(`Uploaded: ${prod.title}`)
                successCount++;
            } catch (productError) {
                console.error(`FAILED: "${prod.title}" — ${productError.message}`);
                failCount++;
            }
        }

        console.log(`\nDone. ${successCount} uploaded, ${failCount} failed.`)

    } catch (error) {
        console.error("Fatal error:", error);
    } finally {
        mongoose.disconnect();
    }
}

bulkUpload();